### ISSUE TITLE
Fix license

### ISSUE THREAD

**Issue by tfmorris** [Git-Lit/git-lit#31]
The current license is GPL v3. Using a software license for text isn't appropriate.  If you really want to stick with a restrictive viral license, you could investigate GFDL or something, but I'd strongly advocate for something liberal along the lines of either a) a PDDL/CC0 or b) the least restrictive license that meets whatever terms the British Library requires.

**Comment by JonathanReeve** [comment]
For the code, I went with the GPL, since GITenberg uses the GPLv3, and that way I wouldn't have to worry about license compatibility. Plus, I think the GPL is awesome. As far as I know, the BL texts are in the public domain, so I'm sure whatever we decide to go with is fine. I'd be in favor of just sticking with the GPL, since it looks like it's being used for text in [a few places](https://en.wikipedia.org/wiki/GNU_General_Public_License#Use_for_text_and_other_media). But I also hear people are using Creative Commons licenses for text, so we could do a CC license, like maybe the CC-BY-SA? I'll look into the licenses you mention.

**Comment by tfmorris** [comment]
As far as I can tell, there's no license in this repo (which is definitely something should be rectified), so that wasn't what I was discussing.

I should have been clearer that I was talking about the license being applied to the public domain texts donated by the British Library.  I view applying GPL or other restrictive licenses to public domain materials as akin to commercial firms selling access to public domain materials.  I wouldn't support it.  If it's in the public domain, it should stay in the public domain.  People who want to restrict access to public domain texts can join TCP, ProQuest, or some other organization that operates that way.

**Comment by sethwoodworth** [comment]
The way the books and code are organized, there are no license encumbrances from one to the other.  The code being GPLv3'd wont mean you can't keep the book repos PD or CC0.

**Comment by eshellman** [comment]
I'd advocate CC0 for the texts.

**Comment by JonathanReeve** [comment]
I just removed the LICENSE file for now. It makes sense to keep this as open as possible.

**Comment by tfmorris** [comment]
> I just removed the LICENSE file for now. It makes sense to keep this as
> open as possible.
> 
> This has the opposite effect. Everything is copyrighted automatically.
> Without a declared license, it's unusable by anyone else. The most open
> license would be CC0 or PD.

**Comment by eshellman** [comment]
Tom's absolutely right!
